// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDailyProcesses() {
  return window['go']['bindings']['DataBinding']['GetDailyProcesses']();
}

export function GetLast30Days() {
  return window['go']['bindings']['DataBinding']['GetLast30Days']();
}
