// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function GetDailyProcesses():Promise<Array<bindings.ProcessUsageData>>;

export function GetLast30Days():Promise<{[key: string]: bindings.TotalDuration}>;
