// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function LoadConfig():Promise<bindings.ConfigDto>;

export function SaveConfig(arg1:bindings.ConfigDto):Promise<void>;
