// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllTimeUsage() {
  return window['go']['bindings']['UsageBinding']['GetAllTimeUsage']();
}

export function GetUsageBetweenDates(arg1, arg2) {
  return window['go']['bindings']['UsageBinding']['GetUsageBetweenDates'](arg1, arg2);
}
