// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {bindings} from '../models';

export function GetUsageBetweenDates(arg1:time.Time,arg2:time.Time):Promise<Array<bindings.UsageInfo>>;
